# Imports

In [2]:
from skimage import color, io, measure, img_as_ubyte
from skimage.measure import profile_line
from skimage.transform import rescale, resize
import matplotlib.pyplot as plt
import numpy as np

/Users/loui/.conda/envs/02502-image-analysis/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


# Exercise 2

In [4]:
# Directory containing data and images
in_dir = "data/"
# X-ray image
im_name = "metacarpals.png"
# Read the image.
# Here the directory and the image name is concatenated
# by "+" to give the full path to the image.
im_org = io.imread(in_dir + im_name)

print(im_org)

[[ 63  67  68 ... 148 148 150]
 [ 65  67  67 ... 147 148 150]
 [ 63  67  67 ... 147 147 150]
 ...
 [ 59  59  60 ... 157 157 160]
 [ 59  57  60 ... 158 159 157]
 [ 51  56  57 ... 160 158 152]]


# Exercise 3

In [1]:
# Display image
io.imshow(im_org)
plt.title('Metacarpal image')
io.show()

NameError: name 'io' is not defined